server:
  port: 8762
eureka:
  client:
    #是否将自己这个服务注册到EurekaServer中  默认True 此服务为Server  所以为False
    registerWithEureka: true
    #是否从EurekaServer获取注册信息 默认True 单点ES不存在其他的EurkaServer 所以为False
    fetchRegistry: true
    serviceUrl:
      #与ES交互的地址 查询注册都依赖此地址 默认为http://localhost:8761/eureka 多个地址使用","分割
      defaultZone: http://eureka01:8761/eureka/,http://eureka03:8763/eureka/
  instance:
    hostname: eureka02
  #是否开启自我保护机制
  server:
    enable-self-preservation: false
spring:
  application:
    name: springcloud-eureka-server-02